// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditModalController from "./edit_modal_controller"
application.register("edit-modal", EditModalController)

import ShowModalController from "./show_modal_controller"
application.register("show-modal", ShowModalController)

import ValidatorController from "./validator_controller"
application.register("validator", ValidatorController)
